export const registerElements = {
  radioGenderMale: '#id_gender1',
  radioGenderFemale: '#id_gender2',
  inputFirstName: '#customer_firstname',
  inputLastName: '#customer_lastname',
  inputEmail: '#email',
  inputPassword: '#passwd',
  selectDayOfBirth: '#days',
  selectMonthOfBirth: '#months',
  selectYearOfBirth: '#years',
  checkboxNewsletter: '#newsletter',
  checkboxOffers: '#optin',
  inputAddressFirstName: '#firstname',
  inputAddressLastName: '#lastname',
  inputCompanyName: '#company',
  inputAddress: '#address1',
  inputComplement: '#address2',
  inputCity: '#city',
  selectState: '#id_state',
  inputPostCode: '#postcode',
  inputAdditionalInfos: '#other',
  inputHomePhone: '#phone',
  inputMobilePhone: '#phone_mobile',
  inputAddressAlias: '#alias',
  buttonRegister: 'Register'
}